name: qutip-lectures
channels:
  - conda-forge
  dependencies:
  - matplotlib=2.1.0=py36hba5de38_0
  - numpy=1.13.3=py36ha12f23b_0
  - scipy=0.19.1=py36h9976243_3
  - cython=0.26.1=py36h21c49d0_0
  - qutip=4.1
